# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: devoteam
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    volumes:
      - /tmp/docker/mysql:/var/lib/mysql
    ports:
      - "43306:3306"
    hostname: mysql_host

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

  activemq:
     image: webcenter/activemq:5.14.3
     restart: always
     ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"